# deployment-cert-manager.yaml
# Define o ClusterIssuer do Let's Encrypt (produção) e o Certificate para o domínio www.work3.com.br.
# Configurado para usar o http01 challenge com Ingress.

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: tarcisio.rocha.engenheiro@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
            serviceType: NodePort # Especifica que o solver use NodePort
---
# certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-work3-com-br-tls
  namespace: work3-app
spec:
  secretName: www-work3-com-br-tls-secret # Nome do Secret onde o certificado será armazenado
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - www.work3.com.br


